export const GET_QUESTIONS = 'GET_QUESTIONS';
export const GET_QUESTION = 'GET_QUESTION';
export const ADD_QUESTION = 'ADD_QUESTION';
export const DELETE_QUESTION = 'DELETE_QUESTION';
export const QUESTIONS_LOADING = 'QUESTIONS_LOADING';
export const END_QUESTIONS_LOADING = 'END_QUESTIONS_LOADING';

export const USER_LOADING = 'USER_LOADING';
export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';

export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';

export const GET_ERRORS = 'GET_ERRORS';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';

export const GET_KEYWORDS = 'GET_KEYWORDS';
export const KEYWORDS_LOADING = 'KEYWORDS_LOADING';

export const ADD_COMMENT = 'ADD_COMMENT';
export const DELETE_COMMENT = 'DELETE_COMMENT';

// Analytics
export const FETCH_QUESTIONS_LINE = 'FETCH_QUESTIONS_LINE';
export const QUESTIONS_LINE_LOADING = 'QUESTIONS_LINE_LOADING';
export const FETCH_QUESTIONS_BAR = 'FETCH_QUESTIONS_BAR';
export const QUESTIONS_BAR_LOADING = 'QUESTIONS_BAR_LOADING';

export const FETCH_KEYWORDS_BAR = 'FETCH_KEYWORDS_BAR';
export const KEYWORDS_BAR_LOADING = 'KEYWORDS_BAR_LOADING';

export const FETCH_USERS_LINE = 'FETCH_USERS_LINE';
export const USERS_LINE_LOADING = 'USERS_LINE_LOADING';

export const FETCH_USER_PROFILE = 'FETCH_USER_PROFILE';
export const USER_PROFILE_LOADING = 'USER_PROFILE_LOADING';
